use_frameworks!

target 'AKUnionPayManager_Example' do
  pod 'AKUnionPayManager', :path => '../'
  
  pod 'AKUnionPaySDK', :git => 'git@github.com:ArtisanKid/AKUnionPaySDK.git'
  #pod 'AKUnionPaySDK', :path => '../../AKUnionPaySDK'
  
  pre_install do |installer|
      # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
      def installer.verify_no_static_framework_transitive_dependencies; end
  end

  target 'AKUnionPayManager_Tests' do
    inherit! :search_paths

    
  end
end
